---
- hosts: all
  become: true
  tasks:
  # - name: Installation des packages de base pour docker
  #   apt:
  #     name:
  #       - apt-transport-https
  #       - ca-certificates
  #       - curl
  #       - gnupg
  #       - lsb-release
  #     update_cache: yes

  # # Ajouter la clé gpg pour la sécurité des échanges avec le serveur des packages docker
  # - name: ajout de la cle gpg
  #   apt_key:
  #     url: https://download.docker.com/linux/debian/gpg
  
  # # Ajouter le repos pour chercher les packages de docker
  # - name: Ajout de l'adresse du repos pour les packages docker de debian
  #   apt_repository:
  #     repo: deb https://download.docker.com/linux/debian stretch stable


  # # Installation des composants docker
  # - name: install docker components
  #   apt:
  #     name:
  #       - docker-ce
  #       - docker-ce-cli
  #       - containerd.io

  # # démarrage du service
  # - name: start docker service
  #   service:
  #     name: docker start
  #     state: started
  #     enabled: true

  - name: create folder
    file:
        path: /DockerSources
        state: directory
        mode: '0755'

  # copie des fichies du TPvote
  - name: file configuration copy
    copy: 
      src: ./../../Prof/TPDocker/
      dest: /DockerSources/
      recurse: yes
  

  # construction des images
  - name: build images
    command: docker build -t {{item}} /DockerSources/TPDocker/{{item}}/.
    loop:
      - vote
      - worker
      - result
  # - name: Build image Avote
  #   docker_image:
  #     name: Avote
  #     path: /DockerSources/vote/
  #     push: yes
  # - name: Build image Aresult
  #   docker_image:
  #     name: Aresult
  #     path: /DockerSources/result/
  #     push: yes
  # - name: Build image Aworker
  #   docker_image:
  #     name: Aworker
  #     path: /DockerSources/worker/
  #     push: yes


  - name: Suppression code source
    command: rm -rf /DockerSources




  # - name: Build image result
  #   command: docker build -t Image_result ./../../Prof/TPDocker/result
  # - name: Build image vote
  #   command: docker build -t Image_result ./../../Prof/TPDocker/vote
  # - name: Build image worker
  #   command: docker build -t Image_result ./../../Prof/TPDocker/worker


  # service:
    # name: apache2
    # state: started
    # enabled: yes

