---
- hosts: all
  become: true
  tasks:
  - name: install apache2
    apt:
      name:
        - apache2
      update_cache: yes

  - name: change folder rights
    file: path=/var/www/html state=directory mode=0755

  - name: file configuration copy
    copy: 
      src: ./index.html
      dest: /var/www/html/
  
  - name: start apache2 service
    shell:
      cmd: systemctl start apache2
  # service:
    # name: apache2
    # state: started
    # enabled: yes

