---
- hosts: all
  become: true
  tasks:
  - name: install git
    apt:
      name:
        - apache2
      update_cache: yes

  - name: Fix 'support_tools' permissions
    file: path=/var/www/html state=directory recurse=yes mode=0777

  - name: file configuration copy
    copy: 
      src: ./index.html
      dest: /var/www/html
  
  - name: Lancement apache2
    shell:
      cmd: systemctl start apache2

